-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Nov 10, 2021 at 12:11 PM
-- Server version: 10.4.21-MariaDB
-- PHP Version: 8.0.10

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `project`
--

-- --------------------------------------------------------

--
-- Table structure for table `posts`
--

CREATE TABLE `posts` (
  `id` int(11) NOT NULL,
  `title` varchar(35) NOT NULL,
  `postcontent` text NOT NULL,
  `userName` varchar(35) NOT NULL,
  `date` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `posts`
--

INSERT INTO `posts` (`id`, `title`, `postcontent`, `userName`, `date`) VALUES
(1, 'Layla', 'What\'ll you do when you get lonely\nAnd nobody\'s waiting by your side?\nYou\'ve been running and hiding much too long\nYou know it\'s just your foolish pride\nLayla, you\'ve got me on my knees\nLayla, I\'m begging, darling please\nLayla, darling won\'t you ease my worried mind\nI tried to give you consolation\nWhen your old man had let you down\nLike a fool, I fell in love with you\nTurned my whole world upside down\nLayla, you\'ve got me on my knees\nLayla, I\'m begging, darling please\nLayla, darling won\'t you ease my worried mind\nLet\'s make the best of the situation\nBefore I finally go insane\nPlease don\'t say I\'ll never find a way\nAnd tell me all my love\'s in vain\nLayla, you\'ve got me on my knees\nLayla, I\'m begging, darling please\nLayla, darling won\'t you ease my worried mind\nLayla, you\'ve got me on my knees\nLayla, I\'m begging, darling please\nLayla, darling won\'t you ease my worried mind.', 'Eric Clapton', '1970-09-09 19:00:00'),
(2, 'Wonderful Tonight', 'It\'s late in the evening\r\nShe\'s wondering what clothes to wear\r\nShe puts on her makeup\r\nAnd brushes her long blonde hair\r\nAnd then she asks me\r\n\"Do I look all right?\"\r\nAnd I say, \"Yes, you look wonderful tonight\"\r\nWe go to a party\r\nAnd every one turns to see\r\nThis beautiful lady\r\nWho\'s walking around with me\r\nAnd then she asks me\r\n\"Do you feel all right?\"\r\nAnd I say, \"Yes, I feel wonderful tonight\"\r\nI feel wonderful because I see the love light in your eyes\r\nThen the wonder of it all is that you just don\'t realize\r\nHow much I love you\r\nIt\'s time to go home now\r\nAnd I\'ve got an aching head\r\nSo I give her the car keys\r\nAnd she helps me to bed\r\nAnd then I tell her\r\nAs I turn out the light\r\nI say, \"My darling you were wonderful tonight\"\r\n\"Oh, my darling, you were wonderful tonight\"', 'Eric Clapton', '1977-05-02 00:00:00'),
(3, 'I Shot the Sheriff', 'I shot the sheriff, but I did not shoot the deputy\r\nI shot the sheriff, but I did not shoot the deputy\r\nAll around in my home town\r\nThey\'re trying to track me down\r\nThey say they want to bring me in guilty\r\nFor the killing of a deputy\r\nFor the life of a deputy, but I say\r\nI shot the sheriff, but I swear it was in self-defense\r\nI shot the sheriff, and they say it is a capital offense\r\nSheriff John Brown always hated me\r\nFor what I don\'t know\r\nEvery time that I plant a seed\r\nHe said, \"Kill it before it grows\"\r\nHe said, \"Kill it before it grows\", I say\r\nI shot the sheriff, but I swear it was in self-defense\r\nI shot the sheriff, but I swear it was in self-defense\r\nFreedom came my way one day\r\nAnd I started out of town\r\nAll of a sudden I see sheriff John Brown\r\nAiming to shoot me down\r\nSo I shot, I shot him down, I say\r\nI shot the sheriff, but I did not shoot the deputy\r\nI shot the sheriff, but I did not shoot the deputy\r\nReflexes got the better of me\r\nAnd what is to be must be\r\nEvery day the bucket goes to the well\r\nBut one day the bottom will drop out\r\nYes, one day the bottom will drop out, but I say\r\nI shot the sheriff, but I did not shoot the deputy, oh no\r\nI shot the sheriff, but I did not shoot the deputy, oh no', 'Eric Clapton', '1973-02-12 00:00:00'),
(4, 'Sunshine of your love', 'It\'s getting near dawn\r\nWhen lights close their tired eyes\r\nI\'ll soon be with you my love\r\nGive you my dawn surprise\r\nI\'ll be with you darling soon\r\nI\'ll be with you when the stars start falling\r\nI\'ve been waiting so long\r\nTo be where I\'m going\r\nIn the sunshine of your love\r\nI\'m with you my love\r\nThe light\'s shining through on you\r\nYes, I\'m with you my love\r\nIt\'s the morning and just we two\r\nI\'ll stay with you darling now\r\nI\'ll stay with you \'til my seas are dried up\r\nI\'ve been waiting so long\r\nTo be where I\'m going\r\nIn the sunshine of your love\r\nI\'m with you my love\r\nThe light\'s shining through on you\r\nYes, I\'m with you my love\r\nIt\'s the morning and just we two\r\nI\'ll stay with you darling now\r\nI\'ll stay with you \'til my seas are dried up\r\nI\'ve been waiting so long\r\nI\'ve been waiting so long\r\nI\'ve been waiting so long\r\nTo be where I\'m going\r\nIn the sunshine of your love', 'Eric Clapton', '1967-11-01 00:00:00'),
(5, 'Cocaine', 'If you want to hang out, you\'ve gotta take her out, cocaine\r\nIf you want to get down, get down on the ground, cocaine\r\nShe don\'t lie, she don\'t lie, she don\'t lie,\r\nCocaine\r\nIf you got that lose, you want to kick them blues, cocaine\r\nWhen your day is done, and you want to ride on cocaine\r\nShe don\'t lie, she don\'t lie, she don\'t lie,\r\nCocaine\r\nIf your day is gone, and you want to ride on, cocaine\r\nDon\'t forget this fact, you can\'t get it back, cocaine\r\nShe don\'t lie, she don\'t lie, she don\'t lie,\r\nCocaine\r\nShe don\'t lie, she don\'t lie, she don\'t lie,\r\nCocaine', 'Eric Clapton', '1976-03-09 00:00:00'),
(6, 'Tears in heaven', 'Would you know my name?\r\nIf I saw you in heaven\r\nWould it be the same?\r\nIf I saw you in heaven\r\nI must be strong\r\nAnd carry on\r\n\'Cause I know I don\'t belong\r\nHere in heaven\r\nWould you hold my hand?\r\nIf I saw you in heaven\r\nWould you help me stand?\r\nIf I saw you in heaven\r\nI\'ll find my way\r\nThrough night and day\r\n\'Cause I know I just can\'t stay\r\nHere in heaven\r\nTime can bring you down\r\nTime can bend your knees\r\nTime can break your heart\r\nHave you begging please\r\nBegging please\r\nBeyond the door\r\nThere\'s peace, I\'m sure\r\nAnd I know there\'ll be no more\r\nTears in heaven\r\nWould you know my name?\r\nIf I saw you in heaven\r\nWould you be the same?\r\nIf I saw you in heaven\r\nI must be strong\r\nAnd carry on\r\n\'Cause I know I don\'t belong\r\nHere in heaven', 'Eric Clapton', '1992-01-08 00:00:00'),
(7, 'Lay down, Sally', 'There is nothing that is wrong In wanting you to stay here with me I know you\'ve got somewhere to go But won\'t you make yourself at home and stay with me? And don\'t you ever leave Lay down, Sally, and rest here in my arms Don\'t you think you want someone to talk to? Lay down, Sally, no need to leave so soon I\'ve been trying all night long just to talk to you Sun ain\'t nearly on the rise We still got the moon and stars above Underneath the velvet skies, love is all that matters Won\'t you stay with me? Don\'t you ever leave Lay down, Sally, and rest here in my arms Don\'t you think you want someone to talk to? Lay down, Sally, and no need to leave so soon I\'ve been trying all night long just to talk to you I long to see the morning light Color in your face so dreamily So don\'t you go and say goodbye You can lay your worries down and stay with me And don\'t you ever leave Lay down, Sally, and rest here in my arms Don\'t you think you want someone to talk to? Lay down, Sally, there\'s no need to leave so soon I\'ve been trying all night long just to talk to you Lay down, Sally, and rest here in my arms Don\'t you think you want someone to talk to? Lay down, Sally, there\'s no need to leave so soon I\'ve been trying all night long just to talk to you', 'Eric Clapton', '2021-10-27 23:35:44'),
(9, 'Old love', 'I can feel your body\r\nWhen I\'m lying in my bed\r\nToo much confusion\r\nGoing \'round through my head\r\nMakes me so angry\r\nTo know that the flame still burns\r\nWhy can\'t I get over?\r\nWhen will I ever learn?\r\nOld love\r\nLeave me alone\r\nOld love\r\nGo on home\r\nI can see your face\r\nBut I know that it\'s not real\r\nJust an illusion\r\nCaused by how I used to feel\r\nMakes me so angry\r\nTo know now that the flame will always burn\r\nNever get over\r\nKnow now that I\'ll never learn\r\nOld love\r\nLeave me alone\r\nOld love\r\nGo on home\r\nTake me home, boys\r\nOld love\r\nLeave me alone\r\nOld love\r\nGo on home', 'Eric Clapton', '1989-11-07 00:00:00'),
(10, 'After midnight', 'After midnight, we\'re gonna let it all hang down\r\nAfter midnight, we\'re gonna chug-a-lug and shout\r\nWe\'re gonna stimulate some action\r\nWe\'re gonna get some satisfaction\r\nWe\'re gonna find out what it is all about\r\nAfter midnight, we\'re gonna let it all hang down (after midnight, after midnight)\r\nAfter midnight, we\'re gonna shake your tambourine (after midnight, after midnight)\r\nAfter midnight, it\'s all gonna be peaches and cream (after midnight, after midnight)\r\nWe\'re gonna cause talk and suspicion\r\nWe\'re gonna give an exhibition\r\nWe\'re gonna find out what it is all about (what it is all about) (what it is all about)\r\nAfter midnight, we\'re gonna let it all hang down (we\'re gonna let it all hang down)\r\n(We\'re gonna let it all hang down)\r\nAfter midnight, we\'re gonna let it all hang down\r\nAfter midnight, we\'re gonna shake your tambourine\r\n(We\'re gonna shake your tambourine) (we\'re gonna shake your tambourine)\r\nAfter midnight, it\'s all gonna be peaches and cream\r\n(We\'re gonna shake your tambourine) (we\'re gonna shake your tambourine)\r\nWe\'re gonna cause talk and suspicion\r\nWe\'re gonna give an exhibition\r\nWe\'re gonna find out what it is all about (what it is all about, what it is all about)\r\nAfter midnight, we\'re gonna let it all hang down (after midnight, after midnight)\r\nAfter midnight, we\'re gonna let it all hang down\r\n(We\'re gonna let it all hang down) we\'re gonna let it all hang down)\r\nAfter midnight, we\'re gonna let it all hang down\r\n(We\'re gonna let it all hang down) (we\'re gonna let it all hang down)\r\nAfter midnight, we\'re gonna let it all hang down\r\n(We\'re gonna let it all hang down) (we\'re gonna let it all hang down)\r\nAfter midnight, we\'re gonna let it all hang down\r\n(We\'re gonna let it all hang down) (we\'re gonna let it all hang down)', 'Eric Clapton', '1970-04-27 00:00:00'),
(11, 'Got to get better in a little while', 'Don\'t you know what\'s wrong with me?\r\nI\'m seeing things I don\'t want to see.\r\nSniffing things that ain\'t no good for me.\r\nI\'m going down fast, won\'t you say a prayer for me?\r\nIt\'s got to get better in a little while.\r\nIt\'s got to get better in a little while.\r\nIt\'s got to get better in a little while.\r\nIt\'s got to get better in a little while.\r\nThe sun\'s got to shine on my guitar someday.\r\nRevolution all across the land.\r\nJust like Sly, you got to take a stand.\r\nPlease don\'t hurt nobody, don\'t knock them down;\r\nGive them a helping hand to get off the ground.\r\nIt\'s got to get better in a little while.\r\nIt\'s got to get better in a little while.\r\nIt\'s got to get better in a little while.\r\nIt\'s got to get better in a little while.\r\nStill one thing that you can do;\r\nFall down on your knees and pray.\r\nI know the Lord\'s gonna answer you.\r\nDon\'t do it tomorrow, do it today.\r\nIt\'s got to get better in a little while.\r\nIt\'s got to get better in a little while.\r\nIt\'s got to get better in a little while.\r\nIt\'s got to get better in a little while.', 'Eric Clapton', '2013-06-27 00:00:00'),
(12, 'While my guitar gently weeps', 'I look at you all, See the love there that\'s sleeping, While my guitar gently weeps I look, at the floor, And I see it needs sweeping, Still my guitar gently weeps I don\'t know why, nobody told you, how to unfold your love I don\'t know how, someone controlled you, they bought and sold you I look, at the world, and I notice it\'s turning, While my guitar gently weeps With every mistake, we must surely be learning, Still my guitar gently weeps I don\'t know how, you were diverted, You were perverted, too. I don\'t know how, you were inverted, No one alerted you I look at you all, See the love there that\'s sleeping, While my guitar gently weeps. Look at you all Still my guitar gently weeps', 'Eric Clapton', '1968-11-22 01:44:54'),
(13, 'Southbound again', 'Southbound again I don\'t know if I\'m going or leaving home\r\nBoy got to be moving\r\nSeems like the boy is bound to roam\r\nSouthbound again got no money I\'ve got no place to go\r\nThat woman\'s with her lover boy\r\nNever want to see her face no more\r\nEvery single time I roll across the rolling River Tyne\r\nI get the same old feeling\r\nEvery time I\'m moving down the line\r\nSouthbound again last night I felt like crying\r\nRight now I\'m sick of living\r\nBut I\'m going to keep on trying.', 'Mark Knopfler', '1978-10-15 22:41:05'),
(14, 'Lady Writer', 'Lady Writer on the TV Talk about the Virgin Mary Reminded me of you Expectations left to come up to yeah Lady writer on the TV Yeah, she had another quality The way you used to look And I know you never read a book Just the way that her hair fell down around her face Then I recall my fall from grace Another time, another place Lady writer on the TV She had all the brains and the beauty The picture does not fit You talked to me when you felt like it Just the way that her hair fell down around her face Then I recall my fall from grace Another time, another place Yes and your rich old man You know he\'d call her a dead ringer You got the same command Plus you mother was a jazz singer Just the way that her hair fell down around her face Then I recall my fall from grace, oh yeah Another time, another place Lady writer on the TV She knew all about a history You couldn\'t hardly write your name I think I want you just the same as the Lady writer on the TV Talking about the Virgin Mary Yeah you know I\'m talking about you and me And the lady writer on the TV Lady writer on the TV Talking about the Virgin Mary Yeah you know I\'m talking about you and me And the lady writer on the TV', 'Mark Knopfler', '1979-06-27 08:44:37'),
(15, 'So far away', 'Here I am again in this mean old town And you\'re so far away from me And where are you when the sun go down? You\'re so far away from me You\'re so far away from me So far I just can\'t see You\'re so far away from me You\'re so far away from me, alright I\'m tired of bein\' in love and bein\' all alone When you\'re so far away from me I\'m tired of makin\' out on the telephone \'Cause you\'re so far away from me You\'re so far away from me You\'re so far I just can\'t see You\'re so far away from me You\'re so far away from me, alright And I get so tired when I have to explain When you\'re so far away from me See you\'ve been in the sun and I\'ve been in the rain And you\'re so far away from me You\'re so far away from me You\'re so far I just can\'t see You\'re so far away from me You\'re so far away from me, take it down So far away from me Oh, you\'re so far away from me Yeah, you\'re so far away from me So far away from me You\'re so far... and you\'re so far away from me You\'re so far... so far away from me You\'re so far away from me So far away from me You\'re so far... so far away from me So far away from me You\'re so far... so far away from me Alright You\'re so far... you\'re just so far away from me', 'Mark Knopfler', '1971-03-20 00:48:06'),
(16, 'Sultans of swings', 'You get a shiver in the dark\r\nIt\'s a raining in the park but meantime-\r\nSouth of the river you stop and you hold everything\r\nA band is blowing Dixie, double four time\r\nYou feel alright when you hear the music ring\r\nWell now you step inside but you don\'t see too many faces\r\nComing in out of the rain they hear the jazz go down\r\nCompetition in other places\r\nUh but the horns they blowin\' that sound\r\nWay on down south\r\nWay on down south\r\nLondon town\r\nYou check out guitar George, he knows-all the chords\r\nMind, it\'s strictly rhythm he doesn\'t want to make it cry or sing\r\nThey said an old guitar is all, he can afford\r\nWhen he gets up under the lights to play his thing\r\nAnd Harry doesn\'t mind, if he doesn\'t, make the scene\r\nHe\'s got a daytime job, he\'s doing alright\r\nHe can play the Honky Tonk like anything\r\nSavin\' it up, for Friday night\r\nWith the Sultans\r\nWe\'re the Sultans of Swing\r\nThen a crowd a young boys they\'re a foolin\' around in the corner\r\nDrunk and dressed in their best brown baggies and their platform soles\r\nThey don\'t give a damn about any trumpet playin\' band\r\nIt ain\'t what they call Rock and Roll\r\nAnd the Sultans\r\nYeah, the Sultans, they play Creole\r\nCreole\r\nAnd then the man he steps right up to the microphone\r\nAnd says at last just as the time bell rings\r\n\"Goodnight, now it\'s time to go home\"\r\nThen he makes it fast with one more thing\r\n\"We are the Sultans\r\nWe are the Sultans of Swing\"', 'Mark Knopfler', '1978-05-19 20:00:00'),
(17, 'Romeo and Juliet', 'A lovestruck Romeo sang the streets a serenade\r\nLaying everybody low with a love song that he made\r\nFinds a streetlight, steps out of the shade\r\nSays something like, \"You and me, babe, how about it?\"\r\nJuliet says, \"Hey, it\'s Romeo, you nearly gave me a heart attack\"\r\nHe\'s underneath the window, she\'s singing, \"Hey, la, my boyfriend\'s back\r\nYou shouldn\'t come around here singing up at people like that\r\nAnyway, what you gonna do about it?\"\r\n\"Juliet, the dice was loaded from the start\r\nAnd I bet, and you exploded into my heart\r\nAnd I forget, I forget the movie song\r\nWhen you gonna realize it was just that the time was wrong, Juliet?\"\r\nCome up on different streets, they both were streets of shame\r\nBoth dirty, both mean, yes, and the dream was just the same\r\nAnd I dreamed your dream for you and now your dream is real\r\nHow can you look at me as if I was just another one of your deals?\r\nWhen you can fall for chains of silver you can fall for chains of gold\r\nYou can fall for pretty strangers and the promises they hold\r\nYou promised me everything, you promised me thick and thin, yeah\r\nNow you just say \"Oh, Romeo, yeah, you know I used to have a scene with him\"\r\n\"Juliet, when we made love, you used to cry\r\nYou said \'I love you like the stars above, I\'ll love you \'til I die\'\r\nThere\'s a place for us, you know the movie song\r\nWhen you gonna realize it was just that the time was wrong, Juliet?\"\r\nI can\'t do the talks like they talk on the TV\r\nAnd I can\'t do a love song like the way it\'s meant to be\r\nI can\'t do everything but I\'ll do anything for you\r\nI can\'t do anything except be in love with you\r\nAnd all I do is miss you and the way we used to be\r\nAll I do is keep the beat, the bad company\r\nAll I do is kiss you through the bars of a rhyme\r\nJulie, I\'d do the stars with you any time\r\n\"Juliet, when we made love you used to cry\r\nYou said \'I love you like the stars above, I\'ll love you \'til I die\'\r\nThere\'s a place for us you know the movie song\r\nWhen you gonna realize it was just that the time was wrong, Juliet?\"\r\nAnd a lovestruck Romeo, he sang the streets a serenade\r\nLaying everybody low with a love song that he made\r\nFind a convenient streetlight, steps out of the shade\r\nHe says something like, \"You and me, babe, how about it?\"\r\n\"You and me, babe, how about it?\"', 'Mark Knopfler', '1981-01-09 09:00:00'),
(18, 'Tunel of love', 'Getting crazy on the waltzers\r\nBut it\'s the life that I choose\r\nHey, sing about the six blade, sing about the switchback\r\nAnd a torture tattoo\r\nAnd I\'ve been riding on a ghost train\r\nWhere the cars, they scream and slam\r\nAnd I don\'t know where I\'ll be tonight\r\nBut I\'d always tell you where I am\r\nIn a screaming ring of faces\r\nI seen her standing in the light\r\nShe had a ticket for the races\r\nYeah, just like me, she was a victim of the night\r\nI put my hand upon the lever\r\nSaid let it rock and let it roll\r\nI had the one-arm bandit fever\r\nThere was an arrow through my heart and my soul\r\nAnd the big wheel keep on turnin\'\r\nNeon burnin\' up above\r\nAnd I\'m just high on the world\r\nCome on and take a low ride with me girl\r\nOn the tunnel of love\r\nYeah, love\r\nIt\'s just a danger\r\nWhen you\'re riding at your own risk\r\nShe said, \"You are the perfect stranger\"\r\nShe said, \"Baby, let\'s keep it like this\"\r\nIt\'s just a cakewalk, twisting baby, yeah, step right up and say\r\n\"Hey mister, give me two, give me two now\r\n\'Cause any two can play\"\r\nAnd the big wheel keep on turning\r\nNeon burnin\' up above\r\nAnd I\'m just high on the world\r\nCome on and take a low ride with me, girl\r\nOn the tunnel of love\r\nOh love, love\r\nWell it\'s been money for muscle on a another whirligig\r\nMoney for muscle and another girl I dig\r\nAnother hustle just to\r\nJust to make it big and rock away, rock away\r\nOh rock away, rock away\r\nAnd girl, it looks so pretty to me\r\nLike it always did\r\nOh, like the Spanish city to me\r\nWhen we were kids\r\nYeah, girl it looks so pretty to me\r\nJust like it always did\r\nOh, like the Spanish city to me\r\nWhen we were kids\r\nWoh la!\r\nCheck it out\r\nShe took off her silver locket\r\nShe said, \"Remember me by this\"\r\nShe put her hand in my pocket\r\nI got a keepsake and a kiss\r\nAnd in the roar of dust and diesel\r\nI stood and watched her walk away\r\nI could have caught up with her easy enough\r\nBut something must have made me stay\r\nAnd the big wheel keep on turning\r\nNeon burnin\' up above\r\nAnd I\'m just high on this world\r\nCome on and take a low ride with me, girl\r\nOn the tunnel of love\r\nYea love, love\r\nOn the tunnel of love\r\nWoah love, love\r\nYeah, now I\'m searchin\' through these carousels and the carnival arcades\r\nSearching everywhere from steeplechase to palisades\r\nIn any shooting gallery where promises are made\r\nTo rock away, rock away\r\nRock away, rock away\r\nFrom Cullercoats to Whitley bay\r\nAnd to rock away\r\nAnd, girl it looks so pretty to me\r\nLike it always did\r\nLike the Spanish city to me\r\nWhen we were kids\r\nGirl, it looks so pretty to me\r\nLike it always did\r\nLike the Spanish city to me\r\nWhen we were kids', 'Mark Knopfler', '1987-10-09 00:00:00'),
(19, 'Walk of life', 'Here comes Johnny singing oldies, goldies\r\n\"Be-Bop-A-Lula, \" \"Baby What I Say\"\r\nHere comes Johnny singing, \"I Gotta Woman\"\r\nDown in the tunnels, trying to make it pay\r\nHe got the action, he got the motion\r\nOh yeah, the boy can play\r\nDedication, devotion\r\nTurning all the night time into the day\r\nHe do the song about the sweet lovin\' woman\r\nHe do the song about the knife\r\nHe do the walk, do the walk of life\r\nYeah, he do the walk of life\r\nWoohoo\r\nHere comes Johnny, gonna tell you the story\r\nHand me down my walkin\' shoes\r\nHere comes Johnny with the power and the glory\r\nBackbeat the talkin\' blues\r\nHe got the action, he got the motion\r\nYeah, the boy can play\r\nDedication, devotion\r\nTurning all the night time into the day\r\nThe song about the sweet lovin\' woman\r\nHe do the song about the knife\r\nThen he do the walk, do the walk of life\r\nYeah, he do the walk of life\r\nWoohoo-hoo\r\nHere comes Johnny singing oldies, goldies\r\n\"Be-Bop-A-Lula, \" \"Baby What I Say\"\r\nHere comes Johnny singing, \"I Gotta Woman\"\r\nDown in the tunnels, trying to make it pay\r\nHe got the action, he got the motion\r\nOh yeah, the boy can play\r\nDedication, devotion\r\nTurning all the night time into the day\r\nAnd after all the violence and double talk\r\nThere\'s just a song in all the trouble and the strife\r\nYou do the walk, yeah, you do the walk of life\r\nHmm, they do the walk of life\r\nWoohoo\r\nWoohoo-hoo\r\nWoohoo-hoo\r\nWoohoo\r\nWoohoo-hoo', 'Mark Knopfler', '1985-11-29 00:00:00'),
(20, 'Money for nothing', 'Now look at them yo-yos, that\'s the way you do it\r\nYou play the guitar on the MTV\r\nThat ain\'t workin\', that\'s the way you do it\r\nMoney for nothin\' and your chicks for free\r\nNow that ain\'t workin\', that\'s the way you do it\r\nLemme tell ya, them guys ain\'t dumb\r\nMaybe get a blister on your little finger\r\nMaybe get a blister on your thumb\r\nWe got to install microwave ovens, custom kitchen deliveries\r\nWe got to move these refrigerators, we got to move these color TVs\r\nSee the little faggot with the earring and the make up\r\nYeah, buddy, that\'s his own hair\r\nThat little faggot got his own jet airplane\r\nThat little faggot, he\'s a millionaire\r\nWe got to install microwave ovens, custom kitchen deliveries\r\nWe got to move these refrigerators, we gotta move these color TVs\r\nWe got to install microwave ovens, custom kitchen deliveries\r\nWe got to move these refrigerators, we got to move these color TVs\r\nLooky here, look out\r\nI shoulda learned to play the guitar\r\nI shoulda learned to play them drums\r\nLook at that mama, she got it stickin\' in the camera man\r\nWe could have some\r\nAnd he\'s up there, what\'s that?\r\nHawaiian noises?\r\nBangin\' on the bongos like a chimpanzee\r\nThat ain\'t workin\', that\'s the way you do it\r\nGet your money for nothin\', get your chicks for free\r\nWe got to install microwave ovens, custom kitchen deliveries\r\nWe got to move these refrigerators, we gotta move these color TVs\r\nListen here\r\nNow that ain\'t workin\' that\'s the way you do it\r\nYou play the guitar on the MTV\r\nThat ain\'t workin\', that\'s the way you do it\r\nMoney for nothin\' and your chicks for free\r\nMoney for nothin\', chicks for free\r\nGet your money for nothin\' and your chicks for free\r\nOoh, money for nothin\', chicks for free\r\nMoney for nothin\', chicks for free (money, money, money)\r\nMoney for nothin\', chicks for free\r\nGet your money for nothin\', get your chicks for free\r\nGet your money for nothin\' and the chicks for free\r\nGet your money for nothin\' and the chicks for free\r\nLook at that, look at that\r\nGet your money for nothin\' (I want my, I want my)\r\nChicks for free (I want my MTV)\r\nMoney for nothin\', chicks for free (I want my, I want my, I want my MTV)\r\nGet your money for nothin\' (I want my, I want my)\r\nAnd the chicks for free (I want my MTV)\r\nGet your money for nothin\' (I want my, I want my)\r\nAnd the chicks for free (I want my MTV)\r\nEasy, easy money for nothin\' (I want my, I want my)\r\nEasy, easy chicks for free (I want my MTV)\r\nEasy, easy money for nothin\' (I want my, I want my)\r\nChicks for free (I want my MTV)\r\nThat ain\'t workin\'\r\nMoney for nothing, chicks for free\r\nMoney for nothing, chicks for free\r\n', 'Mark Knopfler', '1985-06-24 00:00:00'),
(21, 'Brothers in arms', 'These mist covered mountains Are a home now for me But my home is the lowlands And always will be Someday you\'ll return to Your valleys and your farms And you\'ll no longer burn to be Brothers in arms Through these fields of destruction Baptisms of fire I\'ve witnessed your suffering As the battle raged high And though they did hurt me so bad In the fear and alarm You did not desert me My brothers in arms There\'s so many different worlds So many different suns And we have just one world But we live in different ones Now the sun\'s gone to hell and The moon\'s riding high Let me bid you farewell Every man has to die But it\'s written in the starlight And every line in your palm We\'re fools to make war On our brothers in arms', 'Mark Knopfler', '1985-10-14 20:09:19'),
(22, 'Heavy Fuel', 'Last time I was sober, man I felt bad Worst hangover that I ever had It took six hamburgers and scotch all night Nicotine for breakfast just to put me right \'Cos if you wanna run cool If you wanna run cool If you wanna run cool, you got to run On heavy, heavy fuel Heavy, heavy fuel Heavy, heavy fuel My life makes perfect sense Lust and food and violence Sex and money are my major kicks Get me in a fight I like the dirty tricks \'Cos if you wanna run cool If you wanna run cool Yes, if you wanna run cool, you got to run On heavy, heavy fuel Heavy, heavy fuel Heavy, heavy fuel My chick loves a man who\'s strong The things she\'ll do to turn me on I love the babes, don\'t get me wrong Hey, that\'s why I wrote this song I don\'t care if my liver is hanging by a thread Don\'t care if my doctor says I ought to be dead When my ugly big car won\'t a-climb this hill I\'ll write a suicide note on a hundred dollar bill \'Cos if you wanna run cool If you wanna run cool Yes, if you wanna run cool, you got to run On heavy, heavy fuel Heavy, heavy fuel Heavy, heavy fuel Heavy, heavy fuel Heavy, heavy fuel Heavy, heavy fuel Heavy, heavy fuel Heavy, heavy fuel Heavy, heavy fuel Heavy, heavy fuel', 'Mark Knopfler', '1991-11-01 00:00:00');

-- --------------------------------------------------------

--
-- Table structure for table `postsauthors`
--

CREATE TABLE `postsauthors` (
  `id` int(11) NOT NULL,
  `userName` varchar(35) NOT NULL,
  `email` varchar(50) NOT NULL,
  `pword` varchar(30) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `postsauthors`
--

INSERT INTO `postsauthors` (`id`, `userName`, `email`, `pword`) VALUES
(1, 'Eric Clapton', 'ericc@gmail.com', 'layla'),
(2, 'Jimmy Page', 'jpage@google.com', 'password'),
(3, 'Rory Gallagher', 'roryg@gmail.com', 'penny'),
(4, 'Mark Knopfler', 'mk@gmail.com', 'sultan'),
(5, 'Angus Young', 'acdc@gmail.com', 'rockandrolltrain'),
(6, 'Saul Hudson', 'slash@gmail.com', 'rocketqueen'),
(7, 'Eddie Van Halen', 'eddievh@hotmail.com', 'panama');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `posts`
--
ALTER TABLE `posts`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `title` (`title`);

--
-- Indexes for table `postsauthors`
--
ALTER TABLE `postsauthors`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `email` (`email`),
  ADD UNIQUE KEY `userName` (`userName`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `posts`
--
ALTER TABLE `posts`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=25;

--
-- AUTO_INCREMENT for table `postsauthors`
--
ALTER TABLE `postsauthors`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=11;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `posts`
--
ALTER TABLE `posts`
  ADD CONSTRAINT `foreign key` FOREIGN KEY (`userName`) REFERENCES `postsauthors` (`userName`) ON DELETE CASCADE ON UPDATE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
